### ISSUE TITLE
Clearfix on id="dobby-closet"

### ISSUE THREAD

**Issue by SonOfCrypto** [tfrommen/Dobby#10]
dobby sometimes has some floating problems. You can try it with the "nested pages" plugin. in this case it will be fixed with a simple "clear:both" on id="dobby-closet", but maybe not everywhere.

<img width="792" alt="grafik" src="https://user-images.githubusercontent.com/4516161/30770757-0f7b5f6c-a039-11e7-9ddd-a068361ab9fe.png">

**Comment by tfrommen** [comment]
Hi there,

thanks for the issue.

To be honest, I'm not sure I understand what is happening there as Dobby captures **all** there is in the admin notices areas. This means that if there are floating elements without a clearing container, they already/also should have been rendered incorrectly without Dobby activated.

Could you please paste the markup of the `#wpbody-content` element, without the `form`?

Thanks a lot in advance.

Cheers,
Thorsten

**Comment by SonOfCrypto** [comment]
Yes, I think you are right. The problem is the nested pages plugin.

Unfortunately the sourcecode is full of other stuff, but you just need to install the plugin and than you can have a look at the source. https://wordpress.org/plugins/wp-nested-pages

Thank you very much for your time and for this great plugin!
