### ISSUE TITLE
Moving Dobby into the admin bar?

### ISSUE THREAD

**Issue by SonOfCrypto** [tfrommen/Dobby#11]
for me it would be a great feature. maybe you can think about it :)

<img width="425" alt="grafik" src="https://user-images.githubusercontent.com/4516161/30770770-6085ce42-a039-11e7-8c99-80d1e252faab.png">

**Comment by tfrommen** [comment]
duplicate #6 

----

Although I understand something like this might be preferable for some people, I decided to neither make this the default behavior, nor include this at all in Dobby.

My reasoning regarding the former can be found in #6, and the reason behind the latter is simply that I do not want to bloat the plugin even more than it already happened. It started as a single-file plugin, not long after the initial release I moved the JavaScript into a separate file (as it grew), and now even the PHP part grew and grew. I actually thought about refactoring the plugin, but, to be honest, I don't really plan to extend the plugin, feature-wise. So maintaining it in these two files shouldn't be a problem. If I were to add admin bar stuff, I would naturally need to refactor it at the same time.

Hope you understand.

That being said, if you really want to, you can achieve your desired UI yourself by using the plugin settings (i.e., the selectors) exported to JavaScript. If Dobby rendered, create the admin bar node, hide the Dobby notice (or remove it completely), and replicate the _reveal_ function for the admin bar node.

Cheers,
Thorsten

**Comment by SonOfCrypto** [comment]
I totally get your point :) Thank you for that detailed explanation 👍
