### ISSUE TITLE
Shame you let this one go!

### ISSUE THREAD

**Issue by HandyGadget** [tfrommen/Dobby#12]
WooCommerce is now putting out advertising thinly disguised (or not disguised at all) as admin notices in the admin bar.

Come back Dobby — you're needed more than ever!

Terence.

**Comment by tfrommen** [comment]
Hey Terence,

I know that I haven't updated the plugin in a while (and the w.org Plugin Directory informs about that loud and clear), but is there anything else?
There are no bugs that I am aware of and nothing changed in Core, so if there's anything not working for you, what is it?

Cheers,
Thorsten

**Comment by HandyGadget** [comment]
As far as I can see it works as intended.  I just wanted to let you know about something it wasn't designed to do, but that I think it could (maybe should) do.

Personally, I think this corruption of the important messaging purpose will simply lead to more people using code like...

`.notice-error, div.error { display: none !important; }`

in order to stop their clients from seeing this unwanted advertising, and as a result, no doubt other much more important messages will not be seen either. 

This cannot be a good thing for the WordPress community but it remains to be seen just how strong the community can be, and do something about this kind of deliberate misuse of the WordPress API.

**Comment by wormeyman** [comment]
Maybe just bump the readme version to say it works with the latest WordPress version?

**Comment by tfrommen** [comment]
Done.

- https://github.com/tfrommen/Dobby/releases/tag/v1.4.0
- https://wordpress.org/plugins/wp-dobby/

👍
