### ISSUE TITLE
Issue caused for Slider Revolution

### ISSUE THREAD

**Issue by Mer413** [tfrommen/Dobby#13]
#### Version Information

* PHP: 
* WordPress: Version 6.0

#### Steps to Reproduce

1. Activate Dobby
2. Open Slider Revolution dashboard

#### What I Expected
Slider Revolution's Dashboard to stay the same once Dobby was activated
![Slider Revolution without Dobby activated](https://user-images.githubusercontent.com/108109227/175452798-b0bef12e-2f44-4d9c-8efe-6de53622e0a8.png)

#### What Happened Instead
Once activated, Slider Revolution has a duplicate of the main sidebar menu on its dashboard, excess space between modules and top of page, and the modules are far enough down the page that scrolling is required to get to all the information needed.
![Slider Revolution with Dobby activated](https://user-images.githubusercontent.com/108109227/175452988-3893ed2d-78c2-441c-ba4f-c840c833dbdf.png)

I really love this plugin, I haven't been able to find a replacement that does as awesome of a job - also, total Harry Potter fan. Unfortunately I work a lot in Slider Revolution, and find this dashboard issue frustrating to work around. 
This is one of the plugins that gets a rare 5 star rating on our show wppluginsatoz.com. 
Thank you for looking into this, I look forward to hearing back!

**Comment by tfrommen** [comment]
Hi @Mer413,

Thanks for this issue.

I am not using Slider Revolution, so I don't know what could be going on here. I don't think I will find time setting this up locally and investigate, sorry. (Also, I think this is a Premium plugin.)

One thing you could try yourself is disabling Dobby on Slider Revolution pages. Not sure if you can check for that easily enough.

**Comment by Mer413** [comment]
Thank you for getting back to me, I really appreciate it. 

Unfortunately that didn't work, but I just disable Dobby when I am working in Slider Revolution, and switch him back on when I am done. It works - seriously love Dobby!

Have a great day!
