### ISSUE TITLE
Show highest notice level in Dobby notice.

### ISSUE THREAD

**Issue by Zodiac1978** [tfrommen/Dobby#3]
#### Steps to Reproduce:

Use Dobby. ;)

#### What I see

It is always an info notice:
https://github.com/tfrommen/Dobby/blob/master/dobby.php#L63

#### What would be great:

See what level the notices are (info, success, warning, error) and adopt in Dobby level:

I would suggest this order
`info`, `success`, `warning`,`error`

If a higher level is there pick this one for Dobby.

**Comment by tfrommen** [comment]
Hm, I'm not sure I like that - because Dobby's notice would, of course, not look the same all the time.
Also, this would preferably be done in a way that is more heavy in JavaScript - which is no problem.

I'll try it out in the evening...

**Comment by tfrommen** [comment]
This has been implemented in 27798460a5c8b1b3fa03c6f2ce9f070e824a9a79.

Dobby will now render an **error** notice if any errors got captured, a **warning** notice if any warnings got captured, and otherwise an **info** notice.
