### ISSUE TITLE
php error after activating

### ISSUE THREAD

**Issue by SonOfCrypto** [tfrommen/Dobby#5]
I hope it helps :)

-----------

filemtime(): stat failed for /wp-content/plugins/Dobby-master/assets/js/dobby.js

Location:
wp-content/plugins/Dobby-master/dobby.php:76

Callstack:
filemtime()
wp-content/plugins/Dobby-master/dobby.php:76

tfrommen\Dobby\{closure}()
wp-includes/class-wp-hook.php:298

do_action('all_admin_notices')
wp-admin/admin-header.php:263

**Comment by tfrommen** [comment]
Thanks. Should be fixed. The JS file was not included in the ZIP file.

**Comment by SonOfCrypto** [comment]
Great! It is working. Nice idea 👍
