### ISSUE TITLE
Make even more unobtrusive

### ISSUE THREAD

**Issue by marceltt** [tfrommen/Dobby#6]
I think it would be better if you moved this plugin’s interaction to the admin bar to make it even more unobtrusive, something like this:

![screen shot 2017-08-04](https://user-images.githubusercontent.com/100955/28945827-398a0042-78fc-11e7-9c57-40750b489da4.png)

You would only show the admin bar flag if there are notices and clicking it would toggle visibility of the notices. You could even, if possible, only indicate new notices that haven’t been viewed with the notification number counter, and remove it for already viewed notices to lower “notification anxiety”.

**Comment by tfrommen** [comment]
Hi there,

first of all, thank you for taking the time to suggest this. Unfortunately, this is nothing that I want to implement.

The idea behind Dobby is not to replace the whole admin notices UI or rather experience. It's just to slim it down as good as possible. I do not want to remove all kinds of admin notices from where they usually are, and then do something as tiny as an icon in a totally different place (e.g., the admin bar).
I know that the comparison is rather flawed, but try to see Dobby more as someone zip-tying your notices than someone with a minivan driving them to some remote storage container. 😂

I hope that makes sense.

Thanks again,
Thorsten
